# This is a basic workflow to help you get started with Actions

name: Automatic Releases

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Automatic Releases
        # You may pin to the exact commit or the version.
        # uses: marvinpinto/action-automatic-releases@526ce12c6675bbe6e0e9a4169c90d09a3f7ad3e2
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          # GitHub secret token
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # Git tag (for automatic releases)
          automatic_release_tag: latest # optional
          # Should this release be marked as a draft?
          draft: false # optional
          # Should this release be marked as a pre-release?
          prerelease: false # optional, default is true
          # Release title (for automatic releases)
          title: Latest patron counts # optional
          # Assets to upload to the release
          files: |
            Current Semester - Metro.csv
            Current Semester - Southeast.csv
            Previous Semesters.csv
