name: Automatic Releases

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest # optional
          draft: false # optional
          prerelease: false # optional, default is true
          title: Latest patron counts # optional
          files: |
            Current Semester - Metro.csv
            Current Semester - Southeast.csv
            Previous Semesters - Southeast.csv
            Southeast Patron Counts by Semester
