on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
  schedule:
    - cron: "*/5 * * * *"
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vQxkoCYKXenDUvlreJ9fRC3Nj4SNTcSS2UpWS5H4x_IETNdVIEplRcvG0wandu-1beRTWywIf9neZhk/pub?gid=0&single=true&output=csv
          downloaded_filename: Current Semester Southeast.csv
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vTb_XYdGr1wpPbT15zkULW_0VgbDw5Ajo8NNz-VxGeWEa_G7vwwudh9Afm1ANZFR9jcgW8chIXXko7e/pub?gid=0&single=true&output=csv
          downloaded_filename: Current Semester Metro.csv
